Update a.yml

diff --git a/.github/workflows/a.yml b/.github/workflows/a.yml
--- a/.github/workflows/a.yml
+++ b/.github/workflows/a.yml
@@ -11,30 +11,37 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+      # Set up Docker
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v2
 
-      - name: Purging the Resources
-        if: success()
-        run: |
+      # Verify Docker setup
+      - name: Verify Docker installation
+        run: docker --version
+
+      # - name: Purging the Resources
+      #   if: success()
+      #   run: |
 
 
-              # Declare the variables
-              $aName = "hello"
+      #         # Declare the variables
+      #         $aName = "hello"
               
  
-              # Check if $a equals "hello"
-              if ($aName -eq "hello") {
-                Write-Host "/hi/$aName"
-              }
+      #         # Check if $a equals "hello"
+      #         if ($aName -eq "hello") {
+      #           Write-Host "/hi/$aName"
+      #         }
 
-                $b = "bye"
-              if (-not $?) {
-              Write-Host "Failed to purge OpenAI resource."
-              }
+      #           $b = "bye"
+      #         if (-not $?) {
+      #         Write-Host "Failed to purge OpenAI resource."
+      #         }
               
-              # Check if $b equals "bye"
-              if ($b -eq "bye") {
-                Write-Host "/hey/$bye"
-              }
+      #         # Check if $b equals "bye"
+      #         if ($b -eq "bye") {
+      #           Write-Host "/hey/$bye"
+      #         }
 
 
       # - name: Echo Environment Variable
